services:
    db:
      image: postgres
      restart: always
      ports:
      - 5432:5432
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 123
        POSTGRES_DB: "medcloudbr"
      networks:
        - backend

    app:
        build: .
        ports:
            - 3000:3000
            - 3001:3001
        networks:
            - backend
        
networks:
    backend:
        driver: bridge