services:
  install-api:
    image: node
    user: "node"
    working_dir: /home/node
    volumes: 
      - ./:/home/node
    command: "yarn --cwd 'api' install"

  install-app:
    image: node
    user: "node"
    working_dir: /home/node
    volumes:
      - ./:/home/node
    command: "yarn --cwd 'app' install"

  api:
    depends_on:
      install-app:
        condition: service_completed_successfully
      install-api:
        condition: service_completed_successfully

  build-api:
    depends_on:
      install-app:
        condition: service_completed_successfully
      install-api:
        condition: service_completed_successfully

  build:
    depends_on:
      install-app:
        condition: service_completed_successfully
      install-api:
        condition: service_completed_successfully