services:  
    build-api:
      image: node
      user: "node"
      working_dir: /home/node/api
      volumes:
        - ./api:/home/node/api
      command: "yarn build"

    api:
      environment:
        - NODE_ENV=production
      depends_on:
        build-api: 
          condition: service_completed_successfully
      command: "yarn start"
    
    build:
      image: node
      user: "node"
      working_dir: /home/node/app
      volumes: 
        - ./app:/home/node/app
      command: "yarn build"
  
    app:
      environment: 
        - NODE_ENV=production
      command: "yarn start"
      depends_on:
        build:
          condition: service_completed_successfully
